version: '3.3'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 127.0.0.1:9922:22
      - 6080:80
    volumes:
      - .:/code/
      - /dev/shm:/dev/shm
      - ~/.Xauthority:/root/.Xauthority
    environment:
      - DISPLAY=host.docker.internal:0
    # env_file: local.env
